apiVersion: pingcap.com/v1alpha1
kind: TidbCluster
metadata:
  name: database
  namespace: {{ .Release.Namespace }}
spec:
  version: v8.5.3
  timezone: UTC
  pvReclaimPolicy: Retain
  enableDynamicConfiguration: true
  configUpdateStrategy: RollingUpdate
  discovery: {}
  helper:
    image: alpine:3.16.0
  pd:
    baseImage: pingcap/pd
    maxFailoverCount: 1
    replicas: {{ .Values.pd.replicas }}
    requests:
      storage: "1Gi"
    config: {}
  tikv:
    baseImage: pingcap/tikv
    maxFailoverCount: 1
    evictLeaderTimeout: 1m
    replicas: {{ .Values.tikv.replicas }}
    requests:
      storage: "1Gi"
    config:
      storage:
        reserve-space: "0MB"
      rocksdb:
        max-open-files: 256
      raftdb:
        max-open-files: 256
  tidb:
    baseImage: pingcap/tidb
    maxFailoverCount: 1
    replicas: {{ .Values.tidb.replicas }}
    service:
      type: ClusterIP
    config: {}